apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-d9d1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-d9d1"
  template:
    metadata:
      labels:
        app: "myaks-d9d1"
    spec:
      containers:
        - name: "myaks-d9d1"
          image: "dflaskdock.azurecr.io/myaks"
          ports:
          - containerPort: 5000